sunshinejr/SwiftyUserDefaults

- Src/SwiftyUserDefaults.swift
- Tests/SwiftyUserDefaultsTests/main.swift
Hi, :wave:
I've changed a few things to make tests pass in Xcode 6.3β1. Didn't touch the `.podspec`.
> Update to Swift 1.2

- SwiftyUserDefaults.xcodeproj/project.pbxproj
- SwiftyUserDefaultsTests/SwiftyUserDefaultsTests.swift
Code Coverage Report:
Darker lines indicate untested code
> converted Unit Tests to using XCTest framework

- .gitignore
- SwiftyUserDefaults.xcodeproj/project.pbxproj
- SwiftyUserDefaults.xcodeproj/project.xcworkspace/xcshareddata/SwiftyUserDefaults.xcscmblueprint
- SwiftyUserDefaults.xcodeproj/xcshareddata/xcschemes/SwiftyUserDefaults Mac.xcscheme
- SwiftyUserDefaults/SwiftyUserDefaults.h
Tested:
- Builds sucessfully for 10.11 Xcode 7 beta 3
- tests pass
- carthage with --platform mac/ios
Also  added Carthage/Build to gitignore for cleanup
> Add osx target for the framework

- SwiftyUserDefaults.podspec
> Added tvOS support to Podspec

- .travis.yml
- README.md
Fixes #73 
Implemented Travis support. I added a statement to build & test each target. I'm not an expert in Travis but there could be a faster way of doing this. Feel free to improve.
Also added a CI badge to the README.
👍
> Added Travis CI

- .travis.yml
> Try to fix travis failure with tvOS target

- Sources/SwiftyUserDefaults.swift
A teeny tiny method signature change.
> Update for Xcode beta 4

- Package.swift
fix build errors with latest swift toolchain
> spm: add name, reorded arguments

- Sources/Info.plist
Set git tag value to CFBundleShortVersionString in Info.plist as to be able to check the version of framework.
> Bump version

- .travis.yml
This PR just fixes current errors & updates stack a little bit, before I merge all of these into single scheme like we have in [Moya](https://github.com/Moya/Moya).
> Update CI setup & fix warnings

- Sources/Defaults+Subscripts.swift
- Tests/SwiftyUserDefaultsTests/TestHelpers/DefaultsSerializableSpec.swift
> Fix non-optional to optional comparison

- CHANGELOG.md
- LICENSE
- README.md
- Sources/Defaults+Subscripts.swift
- Sources/Defaults.swift
- Sources/DefaultsBridges.swift
- Sources/DefaultsKeys.swift
- Sources/DefaultsSerializable+BuiltIns.swift
- Sources/DefaultsSerializable.swift
- Sources/OptionalType.swift
- SwiftyUserDefaults.xcodeproj/project.pbxproj
- Tests/SwiftyUserDefaultsTests/Codable/Defaults+FrogCodable.swift
- Tests/SwiftyUserDefaultsTests/CustomTypes/Defaults+FrogCustomSerializable.swift
- Tests/SwiftyUserDefaultsTests/NSCoding/Defaults+Color.swift
- Tests/SwiftyUserDefaultsTests/NSCoding/Defaults+FrogSerializable.swift
- Tests/SwiftyUserDefaultsTests/Primitives/Defaults+Bool.swift
- Tests/SwiftyUserDefaultsTests/Primitives/Defaults+Data.swift
- Tests/SwiftyUserDefaultsTests/Primitives/Defaults+Date.swift
- Tests/SwiftyUserDefaultsTests/Primitives/Defaults+Dictionary.swift
- Tests/SwiftyUserDefaultsTests/Primitives/Defaults+Double.swift
- Tests/SwiftyUserDefaultsTests/Primitives/Defaults+Int.swift
- Tests/SwiftyUserDefaultsTests/Primitives/Defaults+String.swift
- Tests/SwiftyUserDefaultsTests/Primitives/Defaults+URL.swift
- Tests/SwiftyUserDefaultsTests/RawRepresentable/Defaults+BestFroggiesEnum.swift
- Tests/SwiftyUserDefaultsTests/TestHelpers/DefaultsSerializableSpec.swift
> Dictionary support.

- CHANGELOG.md
- README.md
- SwiftyUserDefaults.podspec
> [Release] 4.0.0

- CHANGELOG.md
- SwiftyUserDefaults.xcodeproj/project.pbxproj
- SwiftyUserDefaults.xcodeproj/xcshareddata/xcschemes/SwiftyUserDefaults-Package.xcscheme
- SwiftyUserDefaults.xcodeproj/xcshareddata/xcschemes/SwiftyUserDefaults.xcscheme
- SwiftyUserDefaults.xcodeproj/xcshareddata/xcschemes/SwiftyUserDefaultsTests.xcscheme
Use the recommended locales and additional automatic Xcode changes.
> Updated for Xcode 10.2

- .travis.yml
- Cartfile.private
- Cartfile.resolved
- Cartfile_5.0.private
- Cartfile_5.0.resolved
The Swift 5 variants of the Cartfile are no longer needed 🎉
> update Quick & Nimble for Swift 5

- Cartfile.resolved
- README.md
- Sources/Defaults+StringToBool.swift
- Sources/Defaults+Subscripts.swift
- Sources/Defaults.swift
- Sources/DefaultsAdapter.swift
- Sources/DefaultsBridges.swift
- Sources/DefaultsKeyStore.swift
- Sources/DefaultsKeys.swift
- Sources/DefaultsObserver.swift
- Sources/DefaultsSerializable+BuiltIns.swift
- Sources/DefaultsSerializable.swift
- Sources/DefaultsType.swift
- SwiftyUserDefaults.podspec
- SwiftyUserDefaults.xcodeproj/project.pbxproj
- Tests/SwiftyUserDefaultsTests/Built-ins/Defaults+Bool.swift
- Tests/SwiftyUserDefaultsTests/Built-ins/Defaults+Data.swift
- Tests/SwiftyUserDefaultsTests/Built-ins/Defaults+Date.swift
- Tests/SwiftyUserDefaultsTests/Built-ins/Defaults+Dictionary.swift
- Tests/SwiftyUserDefaultsTests/Built-ins/Defaults+Double.swift
- Tests/SwiftyUserDefaultsTests/Built-ins/Defaults+Int.swift
- Tests/SwiftyUserDefaultsTests/Built-ins/Defaults+String.swift
- Tests/SwiftyUserDefaultsTests/Built-ins/Defaults+URL.swift
- Tests/SwiftyUserDefaultsTests/External types/Defaults+BestFroggiesEnum.swift
- Tests/SwiftyUserDefaultsTests/External types/Defaults+FrogCodable.swift
- Tests/SwiftyUserDefaultsTests/External types/Defaults+FrogCustomSerializable.swift
- Tests/SwiftyUserDefaultsTests/External types/Defaults+FrogSerializable.swift
- Tests/SwiftyUserDefaultsTests/TestHelpers/DefaultsSerializableSpec.swift
- Tests/SwiftyUserDefaultsTests/TestHelpers/TestHelper.swift
#201  is change class to struct or protocol.
#199 is swift5.1 Key Path Member Lookup support.
> merge #201 and #199

- CHANGELOG.md
- README.md
- SwiftyUserDefaults.podspec
> [Release] 5.0.0-beta.2

- .travis.yml
- CHANGELOG.md
- Package.swift
- Package@swift-4.2.swift
> Skip building testing libraries for SPM users.

- CHANGELOG.md
- README.md
- SwiftyUserDefaults.podspec
> [Release] 5.0.0-beta.3

- .travis.yml
- CHANGELOG.md
- Cartfile.resolved
- README.md
- Sources/PropertyWrappers.swift
- SwiftyUserDefaults.podspec
> [Release] 5.0.0

- README.md
Added KVO code snippet in README for key defined in extension of DefaultsKeys
> Updated KVO section of README
